apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms-server
    name: sms-server
spec:
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  selector:
    app: sms-server
    tier: backend
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-server
  labels:
    app: sms-server
spec:
  selector:
    matchLabels:
      app: sms-server
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sms-server
        tier: backend
    spec:
      containers:
        - name: sms-server
          image: muellners/finscale-sms-service:latest
          env:
            - name: spring.datasource.driverClassName
              value: org.drizzle.jdbc.DrizzleDriver
            - name: spring.datasource.url
              value: jdbc:mysql:thin://messagemysql:3306/messagegateway
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: username
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: password
          ports:
            - containerPort: 8443
              name: sms-server
