apiVersion: v1
kind: ConfigMap
metadata:
  name: messagemysql-initdb
  labels:
    app: sms-server
data:
  init.sql: |
    # create databases
    CREATE DATABASE IF NOT EXISTS `messagegateway`;
    # create root user and grant rights
    GRANT ALL ON *.* TO 'root'@'%';
