apiVersion: v1
kind: Service
metadata:
  labels:
    app: sms-server
    name: sms-server
spec:
  ports:
    - protocol: TCP
      port: 9191
      targetPort: 9191
  selector:
    app: sms-server
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-server
  labels:
    app: sms-server
spec:
  selector:
    matchLabels:
      app: sms-server
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sms-server
        tier: backend
    spec:
      containers:
        - name: sms-server
          image: muellners/finscale-sms-service:latest
          env:
            - name: DRIVERCLASS_NAME
              value: org.drizzle.jdbc.DrizzleDriver
            - name: PROTOCOL
              value: jdbc
            - name: SUB_PROTOCOL
              value: mysql:thin
            - name: mysql_driver
              value: org.drizzle.jdbc.DrizzleDriver
            - name: mysql_db_url
              value: jdbc:mysql:thin://messagemysql:3306/messagegateway
            - name: mysql_db_uid
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: username
            - name: mysql_db_pwd
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: password
            - name: MYSQL_HOSTNAME
              value: messagemysql
            - name: MYSQL_PORT
              value: '3306'
            - name: MYSQL_DB_UID
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: username
            - name: MYSQL_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: message-db-secret
                  key: password
          ports:
            - containerPort: 8443
              name: sms-server
